name: Push to tst on PR approval

on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev

jobs:
  push-to-tst:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Create clean working directory (exclude workflows and .git)
        run: |
          mkdir temp-tst
          rsync -av --exclude='.git' --exclude='.github/workflows' ./ temp-tst/

      - name: Push code to tst branch (without workflows)
        working-directory: ./temp-tst
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git checkout -b tst
          git add .
          git commit -m "Sync from dev branch after PR approval (excluding workflows)" || echo "Nothing to commit"
          git push -f origin tst
