name: Push to tst on PR approval

on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev

jobs:
  push-to-tst:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up worktree for clean push
        run: |
          mkdir temp-tst
          rsync -av --exclude='.github/workflows' ./ temp-tst/
          cd temp-tst
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b tst
          git add .
          git commit -m "Sync from dev branch after PR approval (excluding workflows)"
          git push -f origin tst
