name: Push to tst on PR approval

on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev

jobs:
  push-to-tst:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0  # fetch full history for pushing

      - name: Remove workflow files
        run: |
          echo "Removing workflow files before pushing to tst branch"
          rm -rf .github/workflows

      - name: Configure git for pushing
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to tst branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b tst
          git add -A
          git commit -m "Sync from dev branch after PR approval (excluding workflows)" || echo "No changes to commit"
          git push -u origin tst --force
