name: Push to tst on PR approval

on:
  push:
    branches:
      - dev

jobs:
  push-to-tst:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Create and switch to tst branch without workflows
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a new branch from dev
          git checkout tst

          

          git add .
          git commit -m "Sync from dev after PR approval (excluding workflows)" || echo "No changes to commit"

      - name: Push to tst branch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin tst --force
