name: Auto Merge dev to tst

on:
  push:
    branches:
      - dev

jobs:
  merge-dev-to-tst:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: |
          git fetch origin tst:tst

      - name: Merge dev into tst
        run: |
          git checkout tst
          git merge dev --no-edit || echo "No changes to merge"
          
      - name: Push merged changes to tst
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin tst
